### ISSUE TITLE
Variance validation  error

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#645]
Using data file FultonPUMS5full.csv, when  I try to run a variance on "income", I get  this error:

[validation_view.py:129 -               create() ] Validation succeeded: [{'variable': 'income', 'statistic': 'variance', 'valid': False, 'message': 'the decision boundary of the predicate is outside the bounds (Exception)'}]

I tried it using data type float and integer, and got the same error.

If I run it on "age", in the same file, I don't get any errors and it successfully creates a DP Variance.

**Comment by ekraffmiller** [comment]
The file is  FultonPUMS5full.csv, located here: https://drive.google.com/file/d/1IVyETS03e2HhBFUXhs1-shv5dCE0-sxs/view?usp=sharing (In OpenDP test data folder)

**Comment by ecowan** [comment]
@ekraffmiller  what epsilon are you setting, and what min/max values are you setting for income?

**Comment by ekraffmiller** [comment]
I used epsilon =1, min=10000, max=500000

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ecowan** [comment]
I was just able to successfully complete the process with epsilon = 0.25 min=0 max=10000 and fixed_value = 10000. 

@raprasad this error is coming from opendp in line 120 of dp_variance_spec.py when we use the binary_search to calculate the scale. My suspicion is that the income amounts are much larger than the other columns we've been testing with, and the process is failing to find a suitable scale as a result. 

I can reproduce the problem by setting the max to a larger value (e.g. 50000)

**Comment by ecowan** [comment]
If we update the binary_search bounds to [0.0, 100_000_000.0] then we can do the DP variance on this data provided that we give clipping bounds of [0.0, 500_000.0]

From a usability perspective, we need to make sure that errors from OpenDP are not making it to the front end. In this case, the user should see something that explains why the requested operation is not possible, in a way that won't leak information about the underlying data set. 

Thanks @Shoeboxam for advising on this!

**Comment by Shoeboxam** [comment]
Specifically on the variance, sigma will be approximately `d_in * (U - L)^2 / n / 2 / eps`. If you let `d_in = 1`, `U, L = 0, 500_000`, `n = 25_767`, and `eps = 1`, then sigma works out to ~4.8 million. Therefore your decision boundary is at ~4.8 mil, but your binary search was bounded by (0, 1 mil). This explains the error, "the decision boundary of the predicate is outside the bounds".

In 0.5.0, you should be able to drop binary search bounds completely, because we've added an exponential bounds search to the binary search utility that will fill these binary search bounds for you.

**Comment by raprasad** [comment]
potential error message. "Please make min and max values for the {variable_name} smaller"
